package gvtmovie;

import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel; 
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

 
public class ConfirmBid extends javax.swing.JDialog {

    private int countChildren, countAdult, countSenior;
   public ConfirmBid() {
        initComponents();
    }
   public ConfirmBid(JFrame f, boolean m, Movie theMovie) { 
        super(f, m);
        initComponents();
          Double countChildren, countAdult, countSenior, totalAmt, totalPST, totalGST, finalAmt;
          Double priceChildren = 7.99;
          Double priceAdult = 10.99;
          Double priceSenior = 8.50;
          countChildren = Double.parseDouble(theMovie.getCountChildren());
          countAdult =  Double.parseDouble(theMovie.getCountAdult());
          countSenior = Double.parseDouble(theMovie.getCountSenior());          
          
          totalAmt = countChildren * priceChildren + countAdult * priceAdult + countSenior * priceSenior; 
          totalPST = totalAmt * 0.07;
          totalGST = totalAmt * 0.05;
          finalAmt = totalAmt + totalPST + totalGST;
//          String temp;
//          temp = String.valueOf(totalPST);
          this.jLabelGST.setText(String.valueOf(Math.round(totalGST*100)/100.0));   
          this.jLabelPST.setText(String.valueOf(Math.round(totalPST*100)/100.0)); 
          this.jLabelTotal.setText(String.valueOf(Math.round(finalAmt*100)/100.0)); 
 
         String optionsFileName = System.getProperty("user.dir") + "\\output_movies.txt";
         jButtonPrint.setVisible(false);
         jButtonReceipt.setVisible(false);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPST = new javax.swing.JLabel();
        jTextName = new javax.swing.JTextField();
        jLabelTitle = new javax.swing.JLabel();
        jButtonPay = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelGST = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTitle1 = new javax.swing.JLabel();
        jLabelTitle2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        Card1 = new javax.swing.JTextField();
        Card4 = new javax.swing.JTextField();
        Card2 = new javax.swing.JTextField();
        Card3 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Card5 = new javax.swing.JTextField();
        Card6 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButtonPrint = new javax.swing.JButton();
        jComboPayMethod = new javax.swing.JComboBox<>();
        jButtonReceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose the deail for payment");

        jLabelPST.setText("jLabel1");

        jLabelTitle.setText("GST(5%)");

        jButtonPay.setText("Pay");
        jButtonPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPayActionPerformed(evt);
            }
        });

        jButtonCancel.setText("cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelGST.setText("jLabel1");

        jLabelTotal.setText("jLabel1");

        jLabel1.setText("Paymethod:");

        jLabelTitle1.setText("Total(CAD, $)");

        jLabelTitle2.setText("PST(7%)");

        jLabel5.setText("Card Number:");

        Card1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card1ActionPerformed(evt);
            }
        });

        jLabel6.setText("Valid until(MM/YYYY)");

        Card5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card5ActionPerformed(evt);
            }
        });

        Card6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Card6ActionPerformed(evt);
            }
        });

        jLabel7.setText("Name:");

        jButtonPrint.setText("Print");
        jButtonPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPrintActionPerformed(evt);
            }
        });

        jComboPayMethod.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Credit", "Debit" }));

        jButtonReceipt.setText("Receipt");
        jButtonReceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonReceiptActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelPST))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelTotal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabelGST)
                            .addComponent(jLabel1)
                            .addComponent(jLabel5))
                        .addGap(54, 54, 54))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButtonPay, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonCancel)
                                .addGap(75, 75, 75)
                                .addComponent(jButtonPrint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonReceipt))
                            .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 5, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Card1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Card5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(Card2, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(6, 6, 6)
                                        .addComponent(Card4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(Card6, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jComboPayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTitle)
                    .addComponent(jLabelTitle1)
                    .addComponent(jLabelTitle2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelGST)
                    .addComponent(jLabelPST)
                    .addComponent(jLabelTotal))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jComboPayMethod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Card4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Card3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Card2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Card1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(Card5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Card6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPay)
                    .addComponent(jButtonCancel)
                    .addComponent(jButtonPrint)
                    .addComponent(jButtonReceipt))
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    
    private void jButtonPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPayActionPerformed
        // TODO add your handling code here: 
//        int bidAmount; 
//        bidAmount = Integer.getInteger(jSpinner1.getValue().toString(),100);  
         
        DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("MMM dd YYYY HH:mm z");
        String text = ZonedDateTime.now().format(FORMATTER); 
        
        
        String name = jTextName.getText();
        boolean allLetters = name.chars().allMatch(Character::isLetter); 
        String errorMessage;
        String cardNumber, cardMM, cardYYYY;
        cardNumber = Card1.getText().trim() + Card2.getText().trim() + Card3.getText().trim() + Card4.getText().trim();
        cardMM = Card5.getText().trim();
        cardYYYY = Card6.getText().trim();
         
        if (allLetters && name.length() > 0 & validatecardMM(cardMM) & validateCardNumber(cardNumber) & validatecardYYYY(cardYYYY)) {
       /////// file write Start  
            String data = "";    
            data = name + "," + jComboPayMethod.getSelectedItem() + "," + Card1.getText()+"-"+Card2.getText()+"-"+Card3.getText()+"-"+Card4.getText() + "," + jLabelTotal.getText() + ","+ text;
 
            BufferedWriter bw = null; 
            try {
               // APPEND MODE SET HERE
               bw = new BufferedWriter(new FileWriter(System.getProperty("user.dir") + "\\output_movies.txt", true));
               bw.write(data);
               bw.newLine();
               bw.flush();
               //errorMessage = "Your name as " + name + " with bid amount " + NumberFormat.getCurrencyInstance(new Locale("en", "CA")).format(jSpinnerChildren.getValue()) + " has been successfully saved.";
               errorMessage = "Payment was successfully completed.";
               displayErrorMessage(errorMessage);
               errorMessage = "If you want to refund, please visit ticket sales representative.";
               displayErrorMessage(errorMessage);
               jButtonPrint.setVisible(true);
               jButtonReceipt.setVisible(true);
            } catch (IOException ioe) {
               ioe.printStackTrace();
            } finally {                       // always close the file
               if (bw != null) try {
                  bw.close();
               } catch (IOException ioe2) {
                  // just ignore it
               }
            }  
       /////// file write End
        }
        else if (!validatecardMM(cardMM) | !validateCardNumber(cardNumber) | !validatecardYYYY(cardYYYY)) {
            errorMessage = "Your Card is wrong!";
            displayErrorMessage(errorMessage);
        }
        else {
            errorMessage = "Your Name is wrong.(only alphabet!)";
            displayErrorMessage(errorMessage);
        }
         
    }//GEN-LAST:event_jButtonPayActionPerformed
    boolean validateCardNumber(String cardNUmber){
        if (cardNUmber.matches("[0-9]{16}")) {
            return true;
        }
        else {
                return false;
                }
    }
    boolean validatecardYYYY(String cardYYYY){
        if (Integer.parseInt(cardYYYY) > 2018 && Integer.parseInt(cardYYYY) < 2030) {
            return true;
        }
        else {
                return false;
                }
    }
    boolean validatecardMM(String cardMM){
        if (cardMM.matches("^(1[0-2]|[1-9])$")) {
            return true;
        }
        else {
                return false;
                }
    } 
    void displayErrorMessage(String errorMessage){
     JOptionPane.showMessageDialog(this, errorMessage);
  }
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void Card1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card1ActionPerformed
        String errorMessage;
        errorMessage = "card1  .";
        displayErrorMessage(errorMessage);
    }//GEN-LAST:event_Card1ActionPerformed
   private void Card2ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }   
   private void Card3ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }   
   private void Card4ActionPerformed(java.awt.event.ActionEvent evt) {                                      
        // TODO add your handling code here:
    }    
    private void Card5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Card5ActionPerformed

    private void Card6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Card6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Card6ActionPerformed

    private void jButtonPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPrintActionPerformed
        String errorMessage;
        errorMessage = "Your ticket is printing....";
        displayErrorMessage(errorMessage);
    }//GEN-LAST:event_jButtonPrintActionPerformed
                     
    private void jButtonReceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonReceiptActionPerformed
        String errorMessage;
        errorMessage = "Your receipt is printing.....";
        displayErrorMessage(errorMessage);
    }//GEN-LAST:event_jButtonReceiptActionPerformed
 
    void addPayListener(ActionListener listenForPayButton){
        jButtonPay.addActionListener(listenForPayButton);
  }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Card1;
    private javax.swing.JTextField Card2;
    private javax.swing.JTextField Card3;
    private javax.swing.JTextField Card4;
    private javax.swing.JTextField Card5;
    private javax.swing.JTextField Card6;
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonPay;
    private javax.swing.JButton jButtonPrint;
    private javax.swing.JButton jButtonReceipt;
    private javax.swing.JComboBox<String> jComboPayMethod;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabelGST;
    private javax.swing.JLabel jLabelPST;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTitle2;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JTextField jTextName;
    // End of variables declaration//GEN-END:variables

    private static class ZoneDateTime {

        private static ZoneDateTime now() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public ZoneDateTime() {
        }
    }
 


}
