package gvtmovie;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Paths;
import java.text.NumberFormat;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.SpinnerModel;
import javax.swing.SpinnerNumberModel; 
import javax.swing.JOptionPane;

public class Payment extends javax.swing.JDialog {

    /**
     * Creates new form ConfirmBid
     */
     public Payment() {
        initComponents();
    }
    public Payment(JFrame f, boolean m, ConfirmBid bid) {
        super(f, m);
        initComponents();
        
        this.jLabelGST.setText(String.valueOf(bid.getCountChildren()));
        this.jLabelGST.setText(String.valueOf(bid.getCountAdult()));
        this.jLabelGST.setText(String.valueOf(bid.getCountSenior()));
        
//        Integer startValue = 0;
//        Integer minValue = 0;
//        Integer maxValue = 10;
//        Integer stepValue = 1;
//        SpinnerModel numModelChildren = new SpinnerNumberModel(startValue, minValue, maxValue, stepValue);
//        SpinnerModel numModelAdult = new SpinnerNumberModel(startValue, minValue, maxValue, stepValue);
//        SpinnerModel numModelSenior = new SpinnerNumberModel(startValue, minValue, maxValue, stepValue);
//        jSpinnerChildren.setModel(numModelChildren);
//        jSpinnerAdult.setModel(numModelAdult);
//        jSpinnerSenior.setModel(numModelSenior);
        // String optionsFileName = System.getProperty("user.dir") + "\\src\\selectcontract\\output_bids.txt";
    }

    Payment(ConfirmBid theBid, boolean b, Movie c) {
        initComponents();
//        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelPST = new javax.swing.JLabel();
        jLabelTitle = new javax.swing.JLabel();
        jButtonSave = new javax.swing.JButton();
        jButtonCancel = new javax.swing.JButton();
        jLabelGST = new javax.swing.JLabel();
        jLabelTotal = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jTextCard1 = new javax.swing.JTextField();
        jTextCard2 = new javax.swing.JTextField();
        jTextCard3 = new javax.swing.JTextField();
        jTextCard4 = new javax.swing.JTextField();
        jLabelTitle1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Choose the deail for payment");

        jLabelPST.setText("jLabel1");

        jLabelTitle.setText("Card Number:");

        jButtonSave.setText("Confirm");
        jButtonSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSaveActionPerformed(evt);
            }
        });

        jButtonCancel.setText("cancel");
        jButtonCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelActionPerformed(evt);
            }
        });

        jLabelGST.setText("jLabel1");

        jLabelTotal.setText("jLabel1");

        jLabel1.setText("Tax");

        jLabel2.setText("GST(5%)");

        jLabel3.setText("PST(7%)");

        jLabel4.setText("Total");

        jRadioButton1.setText("Debit");

        jRadioButton2.setText("Credidt");

        jTextCard1.setText("jTextField1");
        jTextCard1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextCard1ActionPerformed(evt);
            }
        });

        jTextCard2.setText("jTextField1");

        jTextCard3.setText("jTextField1");

        jTextCard4.setText("jTextField1");

        jLabelTitle1.setText("Choose Payment Method");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(233, 233, 233)
                        .addComponent(jButtonSave)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonCancel))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel1)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelTotal))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelPST))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(69, 69, 69)
                                .addComponent(jLabelGST))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34)
                                .addComponent(jTextCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabelTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jRadioButton2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jRadioButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextCard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButton1)
                    .addComponent(jRadioButton2)
                    .addComponent(jLabelTitle1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextCard1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabelTitle))
                    .addComponent(jTextCard4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCard3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextCard2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabelGST))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabelPST))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabelTotal))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSave)
                    .addComponent(jButtonCancel))
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSaveActionPerformed
        // TODO add your handling code here: 
//        int bidAmount; 
//        bidAmount = Integer.getInteger(jSpinner1.getValue().toString(),100); 
 
//        DateTimeFormatter FORMATTER = DateTimeFormatter.ofPattern("MMM dd YYYY HH:mm z");
//        String text = ZonedDateTime.now().format(FORMATTER); 
//       // String name = jTextName.getText();
//        boolean allLetters = name.chars().allMatch(Character::isLetter); 
//        String errorMessage;
//        
//        if (allLetters && name.length() > 0) {
//       /////// file write Start  
//            String data = "";
//            data = name + "," + jLabelGST.getText() + "," + jSpinnerChildren.getValue() + "," + text;
////            try {  
////                 Files.write(Paths.get("C:\\Users\\dojun\\Sync\\ICS125\\Labs\\Lab06\\SelectContract06\\dojun849\\src\\selectcontract\\output_bids.txt"), data.getBytes());
////            } catch (IOException e) {
////                e.printStackTrace();
////            } 
//            BufferedWriter bw = null; 
//            try {
//               // APPEND MODE SET HERE
//               bw = new BufferedWriter(new FileWriter("C:\\Users\\C0472597\\Sync\\ICS125\\Labs\\Lab06\\SelectContract06\\dojun849\\src\\selectcontract\\output_bids.txt", true));
//               bw.write(data);
//               bw.newLine();
//               bw.flush();
//               errorMessage = "Your name as " + name + " with bid amount " + NumberFormat.getCurrencyInstance(new Locale("en", "CA")).format(jSpinnerChildren.getValue()) + " has been successfully saved.";
//               displayErrorMessage(errorMessage);
//            } catch (IOException ioe) {
//               ioe.printStackTrace();
//            } finally {                       // always close the file
//               if (bw != null) try {
//                  bw.close();
//               } catch (IOException ioe2) {
//                  // just ignore it
//               }
//            }  
//       /////// file write End
//        }
//        else {
//            errorMessage = "You must input at least 1 letter with all alphabet!";
//            displayErrorMessage(errorMessage);
//        }
        
        
    }//GEN-LAST:event_jButtonSaveActionPerformed
  void displayErrorMessage(String errorMessage){
     JOptionPane.showMessageDialog(this, errorMessage);
  }
    private void jButtonCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButtonCancelActionPerformed

    private void jTextCard1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextCard1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextCard1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCancel;
    private javax.swing.JButton jButtonSave;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabelGST;
    private javax.swing.JLabel jLabelPST;
    private javax.swing.JLabel jLabelTitle;
    private javax.swing.JLabel jLabelTitle1;
    private javax.swing.JLabel jLabelTotal;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JTextField jTextCard1;
    private javax.swing.JTextField jTextCard2;
    private javax.swing.JTextField jTextCard3;
    private javax.swing.JTextField jTextCard4;
    // End of variables declaration//GEN-END:variables

    private static class ZoneDateTime {

        private static ZoneDateTime now() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public ZoneDateTime() {
        }
    }
 


}
